blank_issues_enabled: false
contact_links:
  - name: â“ Questions
    url: https://github.com/RapidAI/PaddleOCRModelConvert/discussions/categories/q-a
    about: Please use the community forum for help and questions regarding PaddleOCRModelConvert.
  - name: ğŸ’¡ Feature requests and ideas
    url: https://github.com/RapidAI/PaddleOCRModelConvert/discussions/categories/ideas
    about: Please vote for and post new feature ideas in the community forum.
  - name: ğŸ“– Documentation
    url: https://github.com/RapidAI/PaddleOCRModelConvert/wiki
    about: A great place to find instructions and answers about PaddleOCRModelConvert.
