name: Push paddleocr_convert to pypi

on:
  push:
    branches: [ main ]
    paths:
      - 'paddleocr_convert/**'
      - 'docs/doc_whl.md'
      - 'setup.py'
      - '.github/workflows/gen_whl_to_pypi.yml'

jobs:
  GenerateWHL_PushPyPi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Set SSH Environment
        env:
          DEPLOY_KEYS: ${{ secrets.GEN_PYTHON_SDK }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEYS" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*

      - name: Run setup.py
        run: |
          pip install -r requirements.txt
          pip install wheel

          python -m pip install --upgrade pip
          python setup.py bdist_wheel ${{ github.event.head_commit.message }}

      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.RAPIDOCR_OPENVINO }}
          packages_dir: dist/
